using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Emit;
using Microsoft.CodeAnalysis.Text;
using MultiFunPlayer.Common;
using NLog;
using Stylet;
using StyletIoC;
using System.Diagnostics;
using System.IO;
using System.Reflection;
using System.Reflection.Metadata;
using System.Runtime.CompilerServices;
using System.Runtime.Loader;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Channels;
using System.Windows;

namespace MultiFunPlayer.Plugin;

internal sealed class PluginCompilationResult : IDisposable
{
    private PluginAssemblyLoadContext _context;

    public Exception Exception { get; }
    public PluginBase PluginInstance { get; private set; }

    public bool Success => Exception == null;

    private PluginCompilationResult(Exception e) => Exception = e;
    private PluginCompilationResult(PluginAssemblyLoadContext context, PluginBase pluginInstance)
    {
        _context = context;
        PluginInstance = pluginInstance;
    }

    public static PluginCompilationResult FromFailure(PluginAssemblyLoadContext context, Exception e)
    {
#pragma warning disable IDE0059 // Unnecessary assignment of a value
        context?.Dispose();
        context = null;
#pragma warning restore IDE0059 // Unnecessary assignment of a value

        return new(e);
    }

    public static PluginCompilationResult FromSuccess(PluginAssemblyLoadContext context, PluginBase pluginInstance) => new(context, pluginInstance);

    private void Dispose(bool disposing)
    {
        PluginInstance?.InternalDispose();
        PluginInstance = null;

        _context?.Dispose();
        _context = null;
    }

    public void Dispose()
    {
        Dispose(disposing: true);
        GC.SuppressFinalize(this);
    }
}

internal static partial class PluginCompiler
{
    private static Channel<Action> _compileQueue;
    private static Task _compileTask;

    private static Logger Logger { get; } = LogManager.GetCurrentClassLogger();
    private static IContainer Container { get; set; }
    private static IViewManager ViewManager { get; set; }

    private static IReadOnlyCollection<MetadataReference> _referenceCache;
    private static unsafe IReadOnlyCollection<MetadataReference> ReferenceCache
    {
        get
        {
            _referenceCache ??= [.. AppDomain.CurrentDomain.GetAssemblies()
                .Select(a => a.TryGetRawMetadata(out var blob, out var length)
                    ? AssemblyMetadata.Create(ModuleMetadata.CreateFromMetadata((nint)blob, length)).GetReference(filePath: a.Location)
                    : null)
                .NotNull()];

            return _referenceCache;
        }
    }

    private static SyntaxTree _globalUsingsSyntaxTree;
    private static SyntaxTree GlobalUsingsSyntaxTree
        => _globalUsingsSyntaxTree ??= CSharpSyntaxTree.ParseText(
                """
                // <auto-generated/>
                global using global::System;
                global using global::System.ComponentModel;
                global using global::System.Collections.Generic;
                global using global::System.Linq;
                global using global::System.Threading;
                global using global::System.Threading.Tasks;
                global using global::NLog;
                global using global::Stylet;
                global using global::Newtonsoft.Json;
                global using global::Newtonsoft.Json.Linq;
                global using global::MultiFunPlayer.Common;
                global using global::MultiFunPlayer.Input;
                global using global::MultiFunPlayer.Plugin;
                global using global::MultiFunPlayer.Script;
                """,
                path: "GlobalUsings.cs",
                encoding: Encoding.UTF8
            );

    [MethodImpl(MethodImplOptions.NoInlining)]
    public static void QueueCompile(FileInfo pluginFile, Action<PluginCompilationResult> callback)
    {
        _compileQueue ??= Channel.CreateUnbounded<Action>(new UnboundedChannelOptions()
        {
            SingleReader = true,
            SingleWriter = false
        });

        _compileTask ??= Task.Run(DoCompile);
        _compileQueue.Writer.TryWrite(() =>
        {
            Logger.Debug("Compiling plugin [File: {0}]", pluginFile.FullName);
            var result = Compile(pluginFile);
            callback(result);
        });

        static async Task DoCompile()
        {
            await foreach (var compileAction in _compileQueue.Reader.ReadAllAsync())
                compileAction();
        }
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    public static PluginCompilationResult Compile(FileInfo pluginFile)
    {
        var result = InternalCompile(pluginFile);
        GC.Collect(GC.MaxGeneration, GCCollectionMode.Default, blocking: false);
        return result;
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private static PluginCompilationResult InternalCompile(FileInfo pluginFile)
    {
        var context = new PluginAssemblyLoadContext();
        try
        {
            var references = ReferenceCache.ToList();

            var sourceBuffer = File.ReadAllBytes(pluginFile.FullName);
            var encoding = sourceBuffer switch
            {
                [0xff, 0xfe, 0x00, 0x00, ..] => (Encoding)new UTF32Encoding(bigEndian: false, byteOrderMark: true),
                [0x00, 0x00, 0xfe, 0xff, ..] => new UTF32Encoding(bigEndian: true, byteOrderMark: true),
                [0xef, 0xbb, 0xbf, ..] => new UTF8Encoding(encoderShouldEmitUTF8Identifier: true),
                [0xff, 0xfe, ..] => new UnicodeEncoding(bigEndian: false, byteOrderMark: true),
                [0xfe, 0xff, ..] => new UnicodeEncoding(bigEndian: true, byteOrderMark: true),
                _ => new UTF8Encoding(encoderShouldEmitUTF8Identifier: false)
            };

            LoadPluginReferences(pluginFile, encoding.GetString(sourceBuffer), context, references);

            var sourcePath = pluginFile.FullName;
            var pdbPath = Path.ChangeExtension(sourcePath, ".pdb");

            var sourceText = SourceText.From(
                sourceBuffer,
                sourceBuffer.Length,
                encoding,
                canBeEmbedded: true);

            var syntaxTree = CSharpSyntaxTree.ParseText(
                sourceText,
                path: sourcePath
            );

            var pluginClasses = syntaxTree.GetRoot()
                                          .DescendantNodes()
                                          .OfType<ClassDeclarationSyntax>()
                                          .Where(s => s.BaseList?.Types.Any(x => string.Equals(x.ToString(), nameof(PluginBase), StringComparison.OrdinalIgnoreCase)) == true)
                                          .ToList();

            if (pluginClasses.Count == 0)
                return PluginCompilationResult.FromFailure(context, new PluginCompileException("找不到继承 PluginBase 的类"));
            if (pluginClasses.Count > 1)
                return PluginCompilationResult.FromFailure(context, new PluginCompileException("找到了多个继承 PluginBase 的类"));

            var pluginHasConstructors = pluginClasses[0].DescendantNodes()
                                                        .OfType<ConstructorDeclarationSyntax>()
                                                        .Any();
            if (pluginHasConstructors)
                return PluginCompilationResult.FromFailure(context, new PluginCompileException("插件类中不允许定义构造函数，请改用 OnInitialize"));

            var assemblyName = $"Plugin_{Path.GetFileNameWithoutExtension(pluginFile.Name)}";
            var encoded = CSharpSyntaxTree.Create(
                syntaxTree.GetRoot() as CSharpSyntaxNode,
                null,
                sourcePath,
                encoding
            );

            var compilationOptions = new CSharpCompilationOptions(
                outputKind: OutputKind.DynamicallyLinkedLibrary,
                optimizationLevel: Debugger.IsAttached ? OptimizationLevel.Debug : OptimizationLevel.Release,
                warningLevel: 4,
                deterministic: true
            );

            var compilation = CSharpCompilation.Create(
                assemblyName,
                syntaxTrees: [encoded, GlobalUsingsSyntaxTree],
                references: references,
                options: compilationOptions
            );

            var emitOptions = new EmitOptions(
                debugInformationFormat: DebugInformationFormat.PortablePdb,
                pdbFilePath: pdbPath
            );

            using var peStream = new MemoryStream();
            using var pdbStream = new MemoryStream();

            var emitResult = compilation.Emit(
                peStream: peStream,
                pdbStream: pdbStream,
                options: emitOptions,
                embeddedTexts: [EmbeddedText.FromSource(sourcePath, sourceText)]
            );

            if (!emitResult.Success)
            {
                var diagnostics = emitResult.Diagnostics.Where(diagnostic => diagnostic.IsWarningAsError || diagnostic.Severity == DiagnosticSeverity.Error);
                return PluginCompilationResult.FromFailure(context, new PluginCompileException("插件因错误编译失败", diagnostics));
            }

            peStream.Seek(0, SeekOrigin.Begin);
            pdbStream.Seek(0, SeekOrigin.Begin);

            var assembly = context.LoadFromStream(peStream, pdbStream);
            var pluginType = assembly.GetExportedTypes().FirstOrDefault(t => t.IsAssignableTo(typeof(PluginBase)));
            if (pluginType == null)
                return PluginCompilationResult.FromFailure(context, new PluginCompileException("找不到导出的 Plugin 类型"));

            try
            {
                var instance = BuildUpPluginInstance(Activator.CreateInstance(pluginType) as PluginBase);
                return PluginCompilationResult.FromSuccess(context, instance);
            }
            catch (Exception e)
            {
                return PluginCompilationResult.FromFailure(context, e);
            }

            PluginBase BuildUpPluginInstance(PluginBase instance)
            {
                CreateAndBindPluginInstanceView(instance);

                foreach (var property in pluginType.GetProperties(BindingFlags.Instance | BindingFlags.NonPublic)
                                                   .Where(p => p.GetCustomAttribute<InjectAttribute>() != null))
                    property.SetValue(instance, Container.Get(property.PropertyType));

                return instance;
            }

            void CreateAndBindPluginInstanceView(PluginBase instance)
            {
                var view = default(UIElement);
                Execute.OnUIThreadSync(() =>
                {
                    view = instance.CreateView() ?? UIUtils.CreateViewFromFile(Path.ChangeExtension(pluginFile.FullName, ".xaml"));
                    if (view != null)
                        ViewManager.BindViewToModel(view, instance);
                });

                if (view?.GetType().IsAssignableTo(typeof(PluginViewBase)) == false)
                    throw new PluginCompileException("插件视图必须继承 PluginViewBase");
            }
        }
        catch (Exception e)
        {
            Logger.Error(e, "插件编译器发生异常");
            return PluginCompilationResult.FromFailure(context, new PluginCompileException("插件编译器发生异常", e));
        }
    }

    private static void LoadPluginReferences(FileInfo pluginFile, string pluginSource, PluginAssemblyLoadContext context, List<MetadataReference> references)
    {
        foreach (var match in ReferenceRegex.Matches(pluginSource).Where(m => m.Success))
        {
            var reference = match.Groups["value"].Value;
            var added = TryAddByName(reference)
                     || TryAddByPath(Path.Join(pluginFile.DirectoryName, reference))
                     || TryAddByPath(reference);

            if (!added)
                Logger.Warn("Failed to load assembly \"{0}\" for plugin \"{1}\"", reference, pluginFile.Name);
        }

        bool TryAddByPath(string path) => File.Exists(path) && TryAddReference(path, () => context.LoadAndGetReferenceFromAssemblyPath(path));
        bool TryAddByName(string assemblyName) => TryAddReference(assemblyName, () => context.LoadAndGetReferenceFromAssemblyName(new AssemblyName(assemblyName)));

        bool TryAddReference(string reference, Func<MetadataReference> referenceFactory)
        {
            try { references.Add(referenceFactory()); }
            catch (Exception e)
            {
                Logger.Trace(e, "Failed to get reference to assembly \"{0}\" for plugin \"{1}\"", reference, pluginFile.Name);
                return false;
            }

            return true;
        }
    }

    public static void Initialize(IContainer container)
    {
        Container = container;
        ViewManager = container.Get<IViewManager>();
    }

    [GeneratedRegex(@"^//#r\s+""(?<value>.+?)""\s*$", RegexOptions.Multiline)]
    private static partial Regex ReferenceRegex { get; }
}

internal sealed class PluginAssemblyLoadContext() : AssemblyLoadContext(isCollectible: true), IDisposable
{
    private readonly List<AssemblyMetadata> _assemblyMetadata = [];

    protected override Assembly Load(AssemblyName assemblyName) => null;

    public MetadataReference LoadAndGetReferenceFromAssemblyPath(string path) => GetReference(LoadFromAssemblyPath(path));
    public MetadataReference LoadAndGetReferenceFromAssemblyName(AssemblyName assemblyName) => GetReference(LoadFromAssemblyName(assemblyName));

    private unsafe PortableExecutableReference GetReference(Assembly assembly)
    {
        if (!assembly.TryGetRawMetadata(out var blob, out var length))
            throw new BadImageFormatException();

        var moduleMetadata = ModuleMetadata.CreateFromMetadata((nint)blob, length);
        var assemblyMetadata = AssemblyMetadata.Create(moduleMetadata);
        _assemblyMetadata.Add(assemblyMetadata);
        return assemblyMetadata.GetReference(filePath: assembly.Location);
    }

    private void Dispose(bool disposing)
    {
        foreach (var metadata in _assemblyMetadata)
            metadata.Dispose();

        _assemblyMetadata.Clear();
        Unload();
    }

    public void Dispose()
    {
        Dispose(disposing: true);
        GC.SuppressFinalize(this);
    }
}

internal sealed class PluginCompileException : Exception
{
    public PluginCompileException() { }

    public PluginCompileException(string message)
        : base(message) { }

    public PluginCompileException(string message, Exception innerException)
        : base(message, innerException) { }

    public PluginCompileException(string message, IEnumerable<Diagnostic> diagnostics)
        : this($"{message}\n{string.Join('\n', diagnostics.Select(d => d.ToString()))}") { }
}
